version: '2'
services:
    worksorderbook-app:
        image: worksorderbook
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://worksorderbook-mysql:3306/worksorderbook?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    worksorderbook-mysql:
        extends:
            file: mysql.yml
            service: worksorderbook-mysql
